# Generated by Django 4.2.5 on 2023-09-28 09:36

import cloudinary.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('condition', models.IntegerField(choices=[(0, 'Ragged'), (1, 'Worn'), (2, 'Great'), (3, 'Band new')], default=0)),
                ('sold_by', models.CharField(max_length=100)),
                ('size', models.IntegerField(choices=[(0, 'XS'), (1, 'S'), (2, 'M'), (3, 'L'), (4, 'XL')], default=0)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Unisex')], default=0)),
                ('brand', models.IntegerField(choices=[(0, 'Other'), (1, 'Nike'), (2, 'Adidas'), (3, 'GUCCI')], default=0)),
                ('category', models.IntegerField(choices=[(0, 'Headwear'), (1, 'Tops'), (2, 'Trousers'), (3, 'Shoes')], default=0)),
                ('prize', models.IntegerField(default='0')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('product_img', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('liked', models.ManyToManyField(blank=True, related_name='product_likes', to=settings.AUTH_USER_MODEL)),
                ('shoppingcarted', models.ManyToManyField(blank=True, related_name='product_shoppingcarted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
