# Generated by Django 4.2.5 on 2023-09-29 10:37

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=api.models.create_slug, max_length=40, unique=True),
        ),
    ]
