# Generated by Django 4.2.5 on 2023-10-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user_type',
            field=models.CharField(choices=[('STORE', 'STORE'), ('FEAUTURED', 'FEATURED'), ('USER', 'USER')], default='USER', max_length=20),
        ),
    ]
