# Generated by Django 4.2.5 on 2023-11-14 12:23

import api.models
import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_alter_product_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=api.models.create_profile_slug, max_length=40, unique=True)),
                ('profile_pic', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('description', models.TextField(default='', max_length=200)),
                ('location', models.IntegerField(choices=[(0, 'Stockholm'), (1, 'Malmoe'), (2, 'Gothenburg')], default=0)),
                ('follows', models.ManyToManyField(blank=True, related_name='follower', to=settings.AUTH_USER_MODEL)),
                ('products_for_sale', models.ManyToManyField(blank=True, related_name='for_sale', to='api.product')),
                ('username', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
